-- =====================================================
-- Migration: Create app_updates table & policies
-- Run this in your Supabase SQL Editor
-- =====================================================

-- Drop any previous/incomplete version of the table
drop table if exists public.app_updates cascade;

-- Create the complete app_updates table
create table public.app_updates (
  id bigint generated by default as identity primary key,
  version_name text not null,               -- e.g. '1.1.1'
  version_code integer not null unique,     -- e.g. 3 (Android versionCode)
  apk_path text not null,                   -- e.g. 'studyhub-v1.1.1.apk'
  apk_size_bytes bigint,                    -- File size in bytes
  sha256 text,                              -- SHA-256 integrity hash
  release_notes text,                       -- Markdown or changelog
  min_version_code integer default 1,       -- Force update if installed < min_version_code
  force_update boolean default false,       -- Force update flag
  is_active boolean default true,           -- Active release toggle
  created_at timestamptz default now()
);

-- Index for fast version lookup
create index idx_app_updates_version_code on public.app_updates (version_code desc);

-- Enable Row Level Security (RLS)
alter table public.app_updates enable row level security;

-- Policy: Everyone can read active updates
create policy "Allow read access to active updates for everyone"
  on public.app_updates
  for select
  using (is_active = true);
